apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- upstream.yaml

patches:
- path: anonymous-access.yaml
- path: disable-upstream-secret.yaml
- path: disable-upstream-dex.yaml
- path: kustomize-tool-install.yaml
