apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/milnesiidae/ostinato-infra.git
    targetRevision: main
    path: sealed-secrets/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: infra
  syncPolicy:
    automated: {}

